# Generated by Django 4.2 on 2023-04-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company__name'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comp_comments', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comp_tags', to='company.company'),
            preserve_default=False,
        ),
    ]
