# Generated by Django 4.2 on 2023-04-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
