# Generated by Django 4.2 on 2023-04-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='links',
            field=models.JSONField(default=dict),
        ),
    ]
