# Generated by Django 4.2 on 2023-04-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_links'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['company_id', 'slug'], name='video_video_company_44323e_idx'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('company_id', 'slug'), name='unique_video_slug'),
        ),
    ]
