# Generated by Django 4.2 on 2023-04-15 13:38

import api.apps.company.models.company
import api.vendors.mixins.model
from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('alias', models.SlugField(max_length=30, unique=True)),
                ('_name', models.JSONField(blank=True, db_column='name', default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.apps.company.models.company.company_logo_upload_to)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('options', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, api.vendors.mixins.model.CacheMixin),
            managers=[
                ('objs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['alias'], name='company_com_alias_a4ab0f_idx'),
        ),
    ]
