# Generated by Django 4.2 on 2023-04-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='_name',
            field=models.JSONField(blank=True, db_column='name', default=dict),
        ),
    ]
